/**
 * AgriStack Dashboard — Excel → Data Converter
 * Run: node scripts/excel-to-data.js
 *
 * Reads: scripts/AgriStack_Data_Template.xlsx
 * Writes: src/data/usecases.js  (overwrites completely)
 *
 * This is safe to run multiple times. Each run regenerates the data file
 * from whatever is currently in the Excel template.
 */

const XLSX = require('xlsx')
const fs   = require('fs')
const path = require('path')

const TEMPLATE_PATH = path.join(__dirname, 'AgriStack_Data_Template.xlsx')
const OUTPUT_PATH   = path.join(__dirname, '..', 'src', 'data', 'usecases.js')

// ─── Helpers ──────────────────────────────────────────────────────────────────
function readSheet(wb, sheetName) {
  const ws = wb.Sheets[sheetName]
  if (!ws) {
    console.error(`❌  Sheet "${sheetName}" not found in the Excel file.`)
    console.error('    Make sure you are using the correct template file.')
    process.exit(1)
  }
  // header:1 → first row becomes object keys
  return XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' })
}

function yesNo(val) {
  return String(val).trim().toLowerCase() === 'yes'
}

function clean(val) {
  return String(val ?? '').trim()
}

function parseStates(val) {
  const s = clean(val)
  if (!s) return []
  return s.split(',').map(x => x.trim()).filter(Boolean)
}

// ─── Read Excel ───────────────────────────────────────────────────────────────
if (!fs.existsSync(TEMPLATE_PATH)) {
  console.error('❌  Template file not found: ' + TEMPLATE_PATH)
  console.error('    Run this first: node scripts/generate-template.js')
  process.exit(1)
}

console.log('📖  Reading: ' + TEMPLATE_PATH)
const wb = XLSX.readFile(TEMPLATE_PATH)

// ─── Parse USE_CASES sheet ────────────────────────────────────────────────────
const ucRows = readSheet(wb, 'USE_CASES')
// Skip header row (index 0)
const useCases = ucRows.slice(1)
  .filter(row => row[0] && row[1]) // ID and Name must exist
  .map(row => {
    const id       = Number(row[0])
    const name     = clean(row[1])
    const status   = clean(row[2])
    const category = clean(row[3])
    const dept     = clean(row[4])
    const mapper   = clean(row[5])
    const statesRaw= clean(row[6])
    const states   = parseStates(statesRaw)

    // Validate status
    const validStatuses = ['Live', 'In Progress', 'Complete', 'On Hold', 'Pending']
    if (!validStatuses.includes(status)) {
      console.warn(`⚠️   Row ${id} ("${name}"): Unknown status "${status}". Will be stored as-is.`)
    }

    const entry = { id, name, status, category, dept, mapper }
    if (states.length > 0 || category === 'Central' || category === 'Multi') {
      entry.states = states
    }
    return entry
  })

console.log(`✅  USE_CASES: ${useCases.length} rows read`)

// ─── Parse STATES sheet ───────────────────────────────────────────────────────
const stateRows = readSheet(wb, 'STATES')
const stateData = stateRows.slice(1)
  .filter(row => row[0]) // State name must exist
  .map(row => ({
    state:     clean(row[0]),
    mou:       yesNo(row[1]),
    dcs:       yesNo(row[2]),
    fr:        yesNo(row[3]),
    apisTotal: Number(row[4]) || 0,
    apisDone:  Number(row[5]) || 0,
    status:    clean(row[6]),
  }))

console.log(`✅  STATES: ${stateData.length} rows read`)

// ─── Parse MAPPER_APIS sheet ──────────────────────────────────────────────────
const mapperRows = readSheet(wb, 'MAPPER_APIS')
const mappers = mapperRows.slice(1)
  .filter(row => row[0])
  .map(row => ({
    id:    clean(row[0]),
    desc:  clean(row[1]),
    done:  Number(row[2]) || 0,
  }))

console.log(`✅  MAPPER_APIS: ${mappers.length} rows read`)

// ─── Parse CONFIG sheet ───────────────────────────────────────────────────────
const configRows = readSheet(wb, 'CONFIG')
const config = {}
configRows.slice(1).forEach(row => {
  if (row[0]) config[clean(row[0])] = clean(row[1])
})

const enrolledFarmerIds  = config['Enrolled Farmer IDs']  || '—'
const farmerLastUpdated  = config['Enrolled Farmers Last Updated'] || '—'
const dataLastUpdated    = config['Data Last Updated'] || new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })

console.log(`✅  CONFIG: read`)

// ─── Build DONE_COUNTS for mapper APIs ────────────────────────────────────────
const doneCounts = {}
mappers.forEach(m => { doneCounts[m.id] = m.done })

// ─── Generate usecases.js ─────────────────────────────────────────────────────
const ucJson  = JSON.stringify(useCases,  null, 2)
const sdJson  = JSON.stringify(stateData, null, 2)
const mpJson  = JSON.stringify(mappers.map(m => ({ id: m.id, desc: m.desc })), null, 2)
const dcJson  = JSON.stringify(doneCounts, null, 2)

const output = `// ============================================================
// AgriStack Dashboard — Data File
// ============================================================
// ⚠️  DO NOT EDIT THIS FILE MANUALLY.
//     This file is auto-generated by: node scripts/excel-to-data.js
//     Source: scripts/AgriStack_Data_Template.xlsx
//     Last generated: ${new Date().toLocaleString('en-IN')}
// ============================================================

export const DATA_LAST_UPDATED = ${JSON.stringify(dataLastUpdated)}

export const ENROLLED_FARMER_IDS   = ${JSON.stringify(enrolledFarmerIds)}
export const FARMER_DATA_UPDATED   = ${JSON.stringify(farmerLastUpdated)}

export const USE_CASES = ${ucJson}

// State-wise API integration data
export const STATE_API_DATA = ${sdJson}

// Mapper API definitions
export const MAPPER_APIS = ${mpJson}

// Mapper API done counts (number of states with each API integrated)
export const MAPPER_DONE_COUNTS = ${dcJson}

export const STATUS_COLORS = {
  "Live":        { bg: "bg-green-100",  text: "text-green-800",  dot: "bg-green-500"  },
  "In Progress": { bg: "bg-blue-100",   text: "text-blue-800",   dot: "bg-blue-500"   },
  "Complete":    { bg: "bg-purple-100", text: "text-purple-800", dot: "bg-purple-500" },
  "On Hold":     { bg: "bg-amber-100",  text: "text-amber-800",  dot: "bg-amber-400"  },
  "Pending":     { bg: "bg-gray-100",   text: "text-gray-600",   dot: "bg-gray-400"   },
}
`

fs.writeFileSync(OUTPUT_PATH, output, 'utf8')

console.log('')
console.log('🎉  Done! Data file written to: src/data/usecases.js')
console.log('')
console.log('Summary:')
console.log(`   Use Cases  : ${useCases.length}`)
console.log(`   States     : ${stateData.length}`)
console.log(`   Mapper APIs: ${mappers.length}`)
console.log(`   Last Updated: ${dataLastUpdated}`)
console.log('')
console.log('Restart the dashboard to see changes: npm run dev')
